name: Atualizar agenda-salas.json

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Baixar JSON do OneDrive
        run: |
          curl -L \
            -A "Mozilla/5.0" \
            "https://caarn-my.sharepoint.com/:u:/g/personal/fagnerlima_caarn_org_br/IQDx4vuwIPx8Qr4yrkg3dGCDATyw_lT3uD0Wr8eXrVpO74I?download=1" \
            -o agenda-salas.json

          echo "Verificando arquivo baixado:"
          file agenda-salas.json

      - name: Commit se houver alteração
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add agenda-salas.json

          if git diff --cached --quiet; then
            echo "Sem alterações"
          else
            git commit -m "Atualização automática da agenda"
            git push
          fi
