name: Atualizar agenda-salas.json

on:
  schedule:
    - cron: "*/1 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Baixar JSON
        run: |
          curl -L "https://drive.google.com/uc?export=download&id=17Fb9LMVQWDkUFTwU7fapjm4p2ENVUUUF" -o agenda-salas.json

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add agenda-salas.json

          if git diff --cached --quiet; then
            echo "Sem alterações"
          else
            git commit -m "Atualiza agenda"
            git push
          fi
